[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://your-site-name.netlify.app"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [
    "node_modules/@netlify/plugin-nextjs/**/*",
    "node_modules/next/**/*",
    "node_modules/react/**/*",
    "node_modules/react-dom/**/*",
    "node_modules/scheduler/**/*"
  ] 